# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Appium Android

on:
  workflow_dispatch:

jobs:
  appium:
    runs-on: macos-12
    strategy:
      matrix:
        api-level: [ 27 ]
        target: [ default ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.302+8'
          distribution: 'temurin'
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm install -g appium@v1.22.3
          appium -v
          appium &>/dev/null &
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel
          script: mvn test

      - name: Generate artifact for video report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: video_report
          path: ./Android_Pixel4API30/Videos/

      - name: Generate artifact for allure report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure_report
          path: ./allure-results

      - name: Upload artifact for extent reports
        uses: actions/upload-artifact@v3
        with:
          name: cucumber_report
          path: ./target_TestNG/Pixel4API30

      - name: Upload artifact for cucumber reports
        uses: actions/upload-artifact@v3
        with:
          name: Extent
          path: ./Reports

  allure:
    needs: appium
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: allure_report
          path: ./allure-results

      - name: Get AllureReports history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get AllureReports results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10

      - name: Prepare AllureReports deploy to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
